### ISSUE TITLE
Facebook share issue

### ISSUE THREAD

**Issue by subdesign** [jorenvh/laravel-share#4]
Sharing a blog post works well with Twitter, LinkedIn, but Facebook shows the html tags of the first sentence in the share preview window. Is it a FB problem, or maybe you can "strip tags" shared content?
Like (pseudo example): <p>This is the lead text...</p>

**Comment by jorenvh** [comment]
I'm not seeing anything wrong on my side? Can you provide more info please?

![screen shot 2017-05-25 at 13 20 33](https://cloud.githubusercontent.com/assets/8791625/26448345/f97641f0-414c-11e7-84e3-e8801ea910c2.png)

**Comment by JiovannaManriquez** [comment]
Hi, What about your metatags? At view some metatags were forgotten. You can debug and find some errors here:
https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fjorenvanhocht.be%2F

- Inferred Property:  The 'og:url' property should be explicitly provided, even if a value can be inferred from other tags.
- Inferred Property: The 'og:title' property should be explicitly provided, even if a value can be inferred from other tags.
- Inferred Property: The 'og:description' property should be explicitly provided, even if a value can be inferred from other tags.
- Share App ID Missing: The 'fb:app_id' property should be explicitly provided, Specify the app ID so that stories shared to Facebook will be properly attributed to the app. Alternatively, app_id can be set in url when open the share dialog.
- **Propiedad inferida: La propiedad "og:image" debe proporcionarse de forma explícita, incluso si puede deducirse su valor a partir de otras etiquetas.**

Good luck!

**Comment by jorenvh** [comment]
@JiovannaManriquez thanks for the comment, I don't see why this is related to this issue.

Anyway, the package just provides share links, not the meta tags. You should add those by hand in order to display the content you want for facebook,twitter,linkedin,...
