### ISSUE TITLE
Add the ability to configure the Title attribute

### ISSUE THREAD

**Issue by bcismariu** [jorenvh/laravel-share#47]
The `title` attribute should be set for SEO purposes

**Comment by SurfJunky** [comment]
> 
> 
> The `title` attribute should be set for SEO purposes

you can do that trick 

instead of using class or id you can add manually in laravel-share-fa4.php
than use the attr :class or :id as a title.

for example 
`<a title=":id" href=":url" target="_blank" class="yourclass" id="your id">`
in view
`page(null, ['id' => 'your title'])->facebook()`

Hope this help you xD

**Comment by jorenvh** [comment]
PR #50 merged to add support for this
