### ISSUE TITLE
Googleplus and pinterest is missing

### ISSUE THREAD

**Issue by karun-dhir** [jorenvh/laravel-share#60]
Can you add these two

**Comment by jorenvh** [comment]
Pinterest is already supported but not mentioned in the readme apparently. https://github.com/jorenvh/laravel-share/blob/master/src/Share.php#L213-L220

Feel free to create a PR to add it to the docs.

Google plus has been supported but it has been removed since only the business part of google plus is left. I have no intention to support this again.
